command_timeout = 1200
add_newline = false

format = "$os$username$memory_usage$hostname$directory$git_branch$git_commit$git_state$git_status$nodejs$bun$package$cmd_duration$character"

[username]
format = "ğŸ™ [$user | ]($style)"
show_always = true
aliases = { "jose1" = "JoseDv1" }

[directory]
home_symbol = "ğŸ "
truncate_to_repo = false

[git_branch]
always_show_remote = true
format = "[$symbol$branch(:$remote_branch)]($style) "


[git_commit]
only_detached = false
tag_disabled = false

[git_status]
conflicted = "!"
modified = "~"

[bun]
format = '[$symbol\($version\)]($style) '


[package]
disabled = true


[character]
success_symbol = '[âœ](bold green) '
error_symbol = '[âœ—](bold red) '

[memory_usage]
format = "[${ram}]($style) "
disabled = false

[os]
disabled = false
format = "[$symbol]($style)"

[os.symbols]
Ubuntu = "ğŸ§ "
